language: node_js
before_script:
     - "npm install -g se-interpreter"
script:
     - "se-interpreter test.json"
env:
  global:
  matrix:
  - SAUCE_PLATFORM='Windows 8' SAUCE_BROWSER='chrome' SAUCE_BROWSER_VERSION='35'
  - SAUCE_PLATFORM='Windows 8' SAUCE_BROWSER='chrome' SAUCE_BROWSER_VERSION='36'
