language: node_js
before_script:
     - "npm install -g se-interpreter"
script:
     - "se-interpreter Interpreter_config.json"
env:
  global:
  matrix:
  - SAUCE_PLATFORM='Windows 8' SAUCE_BROWSER='FIREFOX' SAUCE_BROWSER_VERSION=''
